import { z } from 'zod';
import type { ExplorerData, ExplorerDetail } from './types';
const record = z.object({id:z.string(),cycleId:z.string(),hospitalId:z.string(),hospital:z.string(),region:z.string(),model:z.string(),year:z.string(),indicatorId:z.string(),indicator:z.string(),category:z.string(),idea:z.string(),status:z.string(),current:z.boolean(),reportType:z.string()});
const count=z.number().int().nonnegative();
const source=z.object({id:z.string(),file:z.string(),record:count,lineStart:count,lineEnd:count,year:z.string(),type:z.string(),raw:z.record(z.string(),z.string())});
const audit=z.object({totalSourceRows:count,includedSourceRows:count,excludedTestRows:count,ambiguousMatches:count,implementationConflicts:count,historicalOther:count,historicalIdeas:count,currentIdeas:count,allHospitals:count,pairs:z.array(z.object({year:z.string(),scope:z.string(),matched:count,denominator:count,numericPairs:count})),sourceFiles:z.array(z.object({name:z.string(),rows:count,sha256:z.string()}))});
export const dataSchema = z.object({records:z.array(record),cycles:z.array(z.object({id:z.string(),hospitalId:z.string(),indicatorId:z.string(),year:z.string(),matched:z.boolean(),hasWorkplan:z.boolean(),numericPair:z.boolean(),periodVerified:z.boolean(),matchStatus:z.string()})),indicators:z.array(z.object({id:z.string(),name:z.string(),unit:z.string(),population:z.string()})),audit,provenance:z.object({scope:z.string(),inputSha256:z.record(z.string(),z.string())})});
export const detailSchema = z.object({id:z.string(),sources:z.array(source),methods:z.array(z.string()),measures:z.array(z.string()),targets:z.array(z.string()),comments:z.array(z.string()),implementationNotes:z.array(z.string()),progressComments:z.array(z.string()),classificationReason:z.string(),classificationRules:z.array(z.string()),classificationVersion:z.string(),secondaryTags:z.array(z.string())});
let cache: Promise<ExplorerData> | undefined;
export function fetchExplorer(): Promise<ExplorerData> { return cache ??= fetch('/data/explorer.json').then(async r => { if (!r.ok) throw new Error(`Unable to load explorer data (${r.status})`); return dataSchema.parseAsync(await r.json()) as Promise<ExplorerData>; }).catch(e => { cache=undefined; throw e; }); }
export async function fetchDetail(id: string): Promise<ExplorerDetail> { const r=await fetch(`/data/details/${encodeURIComponent(id)}.json`); if (!r.ok) throw new Error(`Unable to load detail (${r.status})`); return detailSchema.parse(await r.json()) as ExplorerDetail; }
