'use client'
import { useMemo, useRef, useState } from 'react'
import type { ExplorerDetail, ExplorerRecord } from '@/lib/types'
import { Badge } from '@/components/ui/badge'
import { RecordDetail } from './record-detail'
import { hospitalCycles, hospitalNames, hospitalProfile } from '@/lib/hospital-helpers'
import { fetchDetail as loadDetail } from '@/lib/data'
export function HospitalExplorer({ records, fetchDetail = loadDetail }: { records: ExplorerRecord[]; fetchDetail?: (id: string) => Promise<ExplorerDetail> }) {
 const request=useRef(0); const hospitals=useMemo(()=>hospitalNames(records),[records]); const [hospital,setHospital]=useState(''); const activeHospital=hospitals.includes(hospital)?hospital:(hospitals[0]??''); const profile=useMemo(()=>hospitalProfile(records,activeHospital),[records,activeHospital]); const cycles=useMemo(()=>hospitalCycles(records,activeHospital),[records,activeHospital]); const [selected,setSelected]=useState<ExplorerRecord>(); const [detail,setDetail]=useState<ExplorerDetail|null>(null); const [error,setError]=useState(''); const [loading,setLoading]=useState(false)
 const open=async(r:ExplorerRecord)=>{const token=++request.current;setSelected(r);setDetail(null);setError('');setLoading(true);try{const result=await fetchDetail(r.id);if(token===request.current)setDetail(result)}catch(e){if(token===request.current)setError(e instanceof Error?e.message:'Unable to load source detail.')}finally{if(token===request.current)setLoading(false)}}
 return <div className="space-y-6"><label className="block text-sm font-medium">Hospital<select aria-label="Select hospital" className="mt-1 block h-10 w-full max-w-lg rounded-md border bg-white px-3" value={activeHospital} onChange={e=>setHospital(e.target.value)}>{hospitals.map(h=><option key={h}>{h}</option>)}</select></label>{!activeHospital?<p className="border p-6 text-sm text-slate-600">No hospitals are available for the selected filters.</p>:<><div className="grid gap-3 border-y py-4 sm:grid-cols-2 lg:grid-cols-4"><div><p className="text-xs uppercase text-slate-500">Hospital</p><p className="font-semibold">{profile.name}</p></div><div><p className="text-xs uppercase text-slate-500">Region / model</p><p>{profile.region} · {profile.model}</p></div><div><p className="text-xs uppercase text-slate-500">Years represented</p><p>{profile.years.join(', ')||'Unavailable'}</p></div><div><p className="text-xs uppercase text-slate-500">Status</p><div className="flex flex-wrap gap-1">{profile.statuses.map(s=><Badge key={s.name} variant="outline">{s.name}: {s.count}</Badge>)}</div></div></div><div className="grid gap-6 md:grid-cols-2"><section><h3 className="font-semibold">Indicators targeted</h3><p className="text-sm text-slate-600">{profile.indicators.join(' · ')||'Unavailable'}</p></section><section><h3 className="font-semibold">Intervention categories used</h3><p className="text-sm text-slate-600">{profile.categories.join(' · ')||'Unavailable'}</p></section></div><div className="space-y-5"><h2 className="text-lg font-semibold">Reporting timeline</h2>{cycles.map(c=><section key={c.year} className="border-t pt-4"><h3 className="font-medium">{c.year==='2024/25'?'2024/25 Workplan → 2025/26 Progress Report':c.year==='2025/26'?'2025/26 Workplan → 2026/27 Progress Report':'2026/27 Current Workplan'}</h3>{c.groups.map(group=><div key={group.indicator} className="mt-3"><h4 className="text-sm font-semibold">{group.indicator}</h4>{group.records.map(r=><button key={r.id} onClick={()=>open(r)} className="mt-1 block w-full border p-3 text-left hover:bg-slate-50"><div className="flex flex-wrap justify-between gap-2"><span className="text-sm">{r.idea}</span><Badge variant="outline">{r.status}</Badge></div><p className="mt-1 text-xs text-slate-500">{r.category} · {r.reportType}</p></button>)}</div>)}{!c.records.length&&<p className="mt-2 text-sm text-slate-500">No records reported for this cycle.</p>}</section>)}</div></>}{selected&&<RecordDetail record={selected} detail={detail} loading={loading} error={error} onRetry={()=>selected&&open(selected)} open={Boolean(selected)} onOpenChange={o=>!o&&setSelected(undefined)}/>}</div>
}
