'use client';
import {useEffect,useState} from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
const topics=[['QIP structure and scope','Workplans describe planned change ideas, methods and process targets. The next fiscal year’s progress report records implementation flags and submitted measurements. Exploration covers eight reviewed ED indicators; source-wide audits cover all hospital indicators.'],['Normalization and matching','Explicit mappings preserve hospital and indicator identity. Exact organization–indicator cycle matches are accepted only when unambiguous. Ideas are linked by original text within each cycle. Different ideas and repeated source-detail rows are not interchangeable.'],['Intervention taxonomy','Reproducible text-pattern rules assign one primary category, with a documented Other fallback. Classifications are reviewable labels, not independently validated facts. Each detail record retains taxonomy version and matching rules.'],['Implementation reporting','Implemented and Not implemented follow source Y/N flags. Contradictory flags for the same idea are Conflicting. No usable flag is Unavailable. Coverage counts reported statuses, including conflicts, divided by historical idea associations; it is not a completion rate.'],['Reporting periods and restraint','Workplan and report years do not establish measurement windows. Numeric availability does not prove comparability. The explorer calculates no performance change, improvement, target-attainment or effectiveness metrics, and does not rank hospital performance or infer causality.'],['Counting, filters and traceability','One initiative is a distinct change-idea association within a hospital–indicator cycle. Repeated detail rows are consolidated. Historical and current counts stay separate. All filters use source attributes. Source details retain filenames, report years, record numbers, physical line spans and original fields. Unavailable values remain unavailable; source zero remains zero.']];
const docs=[['methodology','Pipeline methodology'],['data-profile','Original data profile'],['taxonomy-review','Taxonomy review'],['reporting-period-review','Reporting-period review'],['indicator-metadata','Indicator metadata'],['frontend-methodology','Frontend analytical definitions']];
export function Methodology(){
 const [document,setDocument]=useState('methodology'),[text,setText]=useState('Loading methodology…');
 useEffect(()=>{let active=true;fetch(`/documentation/${document}.md`).then(r=>r.ok?r.text():Promise.reject()).then(t=>{if(active)setText(t)}).catch(()=>{if(active)setText('Documentation is unavailable.')});return()=>{active=false}},[document]);
 return <article className="space-y-6"><div className="border-l-4 border-secondary bg-[#edf5f5] p-4 text-sm leading-6"><strong>Current analytical policy.</strong> Reporting periods have not been verified as directly comparable. Numeric source values are available for inspection; outcome and effectiveness metrics are unavailable.</div><div className="grid gap-5 md:grid-cols-2">{topics.map(([title,body])=><section key={title} className="rounded border border-slate-200 bg-white p-5"><h2 className="font-semibold text-primary">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{body}</p></section>)}</div><section className="rounded border border-slate-200 bg-white p-5"><h2 className="section-heading">Technical documentation</h2><p className="mt-2 text-sm leading-6 text-slate-600">Original documentation is preserved below. Earlier calculation specifications and examples are historical technical context; the current policy above supersedes them and does not authorize outcome metrics.</p><label htmlFor="documentation" className="mt-4 block text-sm font-medium">Document</label><select id="documentation" className="my-2 h-10 max-w-full rounded border border-slate-300 bg-white px-3 text-sm" value={document} onChange={e=>{setDocument(e.target.value);setText('Loading documentation…')}}>{docs.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><p className="mb-4 text-xs"><a className="text-primary underline" href={`/documentation/${document}.md`}>Download original Markdown</a></p><div className="prose"><ReactMarkdown remarkPlugins={[remarkGfm]} components={{table:({children})=><div tabIndex={0} role="region" aria-label="Documentation table" className="overflow-x-auto"><table>{children}</table></div>,a:({href,children})=><a href={href?.endsWith('.md')&&!href.startsWith('http')?`/documentation/${href.split('/').pop()}`:href}>{children}</a>}}>{text}</ReactMarkdown></div></section></article>;
}
