"use client";
import Link from 'next/link';
import {Info, ArrowRight} from 'lucide-react';
import {CountChart} from './count-chart';
import {Tooltip,TooltipContent,TooltipProvider,TooltipTrigger} from './ui/tooltip';
import {formatCount,pageModel} from '@/lib/presentation';
import type {FilterKey} from '@/lib/types';
export function Overview({model,onDrill}:{model:ReturnType<typeof pageModel>;onDrill:(key:FilterKey,value:string)=>void}){
 const s=model.summary;
 const kpis=[['Hospitals represented',formatCount(s.hospitals),'Reporting organizations across selected historical and current records. Organizations may cover multiple sites.'],['Historical improvement initiatives',formatCount(s.historicalInitiatives),'Distinct change-idea associations in the 2024/25 and 2025/26 workplan cycles, including unmatched records.'],['Current 2026/27 planned initiatives',formatCount(s.currentInitiatives),'Current workplan associations; no subsequent implementation report is available.'],['Intervention categories',formatCount(s.categories),'Observed primary categories in the selection, including Other.'],['Matched workplan/progress cycles',formatCount(s.matchedCycles),'Distinct historical hospital–indicator cycles represented in the selection with an accepted report match. This does not establish measurement comparability.'],['Implementation-status coverage',s.implementationStatusCoverage===null?'Unavailable':`${s.implementationStatusCoverage.toFixed(1)}%`,'Historical ideas with reported Implemented, Not implemented, or Conflicting status / all selected historical ideas. This measures reporting coverage, not implementation success.']];
 return <div className="space-y-6"><TooltipProvider><div data-tour="kpi-summary" className="grid grid-cols-2 gap-3 xl:grid-cols-6">{kpis.map(([label,value,help])=><div key={label} className="rounded border border-slate-200 bg-white px-4 py-4"><div className="flex items-start justify-between gap-2"><p className="min-h-10 text-xs font-medium leading-5 text-slate-600">{label}</p><Tooltip><TooltipTrigger asChild><button aria-label={`About ${label}`} className="p-1 text-slate-500"><Info size={14}/></button></TooltipTrigger><TooltipContent>{help}</TooltipContent></Tooltip></div><p className="mt-2 text-2xl font-semibold tracking-tight text-primary tabular-nums">{value}</p>{label==='Implementation-status coverage'&&<p className="mt-1 text-xs text-slate-600">{s.implementationStatusReported} of {s.historicalInitiatives} historical ideas</p>}</div>)}</div></TooltipProvider>
 <div data-tour="reporting-limitation" className="flex flex-wrap items-start justify-between gap-3 border-l-4 border-secondary bg-[#edf5f5] px-4 py-3 text-sm"><p className="max-w-3xl leading-6">This explorer describes planning and implementation. Reporting periods are <strong>not comparable</strong>; outcome and effectiveness metrics are unavailable.</p><Link href="/reporting-quality" className="inline-flex items-center gap-1 font-medium text-primary underline underline-offset-4">Review data quality <ArrowRight size={14}/></Link></div>
 <div><h2 className="section-heading">Historical planning & implementation</h2><p className="mt-1 text-sm text-slate-600">Counts combine the selected historical workplan cycles. Coverage differs by year; these are activity counts, not a trend or a hospital ranking.</p></div>
 <div data-tour="improvement-activity" className="grid min-w-0 gap-5 lg:grid-cols-2"><CountChart title="Intervention categories" description="One primary category per idea." data={model.categories} sampleSize={model.historical.length} onSelect={v=>onDrill('category',v)}/><CountChart title="ED indicators receiving improvement activity" data={model.indicators} sampleSize={model.historical.length} onSelect={v=>onDrill('indicator',v)}/><CountChart title="Initiatives by hospital model" data={model.models} sampleSize={model.historical.length} onSelect={v=>onDrill('model',v)}/><CountChart title="Initiatives by region" data={model.regions} sampleSize={model.historical.length} onSelect={v=>onDrill('region',v)}/><CountChart title="Reported implementation status" description="Unavailable and conflicting reports remain visible." data={model.statuses} sampleSize={model.historical.length} onSelect={v=>onDrill('status',v)}/><CountChart title="Intervention category by hospital model" description="Historical idea associations, grouped by reported model." data={model.matrix} series={model.modelNames} sampleSize={model.historical.length} stacked/></div>
 <CountChart title="Historical vs current-plan intervention categories" description={`Historical: n = ${model.historical.length}; current 2026/27: n = ${model.current.length}. Unequal periods and reporting coverage; counts are not a time trend.`} data={model.comparison} series={['Historical','Current 2026/27']} sampleSize={model.records.length}/>
 </div>;
}
