"use client";
import {useEffect,useRef,useState} from 'react';
import {usePathname} from 'next/navigation';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import {Clipboard,MessageCircle,Send,Trash2} from 'lucide-react';
import {useExplorer} from './explorer-provider';
import {Button} from './ui/button';
import {Sheet,SheetContent,SheetDescription,SheetHeader,SheetTitle} from './ui/sheet';
type Chat={role:'user'|'assistant';content:string};
const CHAT_STORAGE_KEY='qip-assistant-chat';
const suggestions=['What is this project?','What is a Quality Improvement Plan?','What does implementation-status coverage mean?','What is an intervention category?','Why are outcome metrics unavailable?','What is ambulance offload time?','How do I use the filters?'];
function savedMessages():Chat[]{
 if(typeof window==='undefined')return [];
 try{const parsed:unknown=JSON.parse(window.sessionStorage.getItem(CHAT_STORAGE_KEY)||'[]');return Array.isArray(parsed)&&parsed.every(item=>typeof item==='object'&&item!==null&&('role' in item)&&((item as Chat).role==='user'||(item as Chat).role==='assistant')&&('content' in item)&&typeof (item as Chat).content==='string')?parsed as Chat[]:[];}catch{return [];}
}
export function ProjectAssistant(){
 const [open,setOpen]=useState(false),[input,setInput]=useState(''),[messages,setMessages]=useState<Chat[]>(savedMessages),[loading,setLoading]=useState(false);const inputRef=useRef<HTMLInputElement>(null),messagesEndRef=useRef<HTMLDivElement>(null);const pathname=usePathname();const {filters}=useExplorer();
 useEffect(()=>{const show=()=>setOpen(true);window.addEventListener('open-project-assistant',show);return()=>window.removeEventListener('open-project-assistant',show);},[]);
 useEffect(()=>{if(open)setTimeout(()=>inputRef.current?.focus(),0);},[open]);
 useEffect(()=>{if(messages.length)window.sessionStorage.setItem(CHAT_STORAGE_KEY,JSON.stringify(messages.slice(-16)));else window.sessionStorage.removeItem(CHAT_STORAGE_KEY);},[messages]);
 useEffect(()=>{messagesEndRef.current?.scrollIntoView({block:'end',behavior:'auto'});},[messages,loading]);
 useEffect(()=>{if(open&&!loading)inputRef.current?.focus();},[loading,open]);
 async function submit(question=input){const message=question.trim();if(!message||loading)return;setInput('');const next=[...messages,{role:'user' as const,content:message}];setMessages(next);setLoading(true);try{const active=Object.fromEntries(Object.entries(filters).filter(([,value])=>value));const response=await fetch('/api/assistant',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message,history:messages.slice(-8),pageContext:{pathname,filters:active}})});const body=await response.json().catch(()=>null);setMessages([...next,{role:'assistant',content:typeof body?.answer==='string'?body.answer:"I couldn't answer that right now. The dashboard itself is still available."}]);}catch{setMessages([...next,{role:'assistant',content:"I couldn't answer that right now. The dashboard itself is still available."}]);}finally{setLoading(false);}}
 const copy=async()=>{const answer=[...messages].reverse().find(message=>message.role==='assistant')?.content;if(answer)await navigator.clipboard?.writeText(answer);};
 return <><Button className="fixed bottom-5 right-5 z-30 shadow-sm" onClick={()=>setOpen(true)} aria-label="Ask about the data"><MessageCircle size={17}/>Ask about the data</Button><Sheet open={open} onOpenChange={setOpen}><SheetContent className="flex w-full flex-col p-0 sm:max-w-xl"><SheetHeader className="mb-0 border-b border-slate-200 px-6 py-5"><SheetTitle>Ontario Hospital QIP Assistant</SheetTitle><SheetDescription>Ask what this project shows, how to use it, or what the data means.</SheetDescription></SheetHeader><div className="min-h-0 flex-1 overflow-y-auto px-6 py-5" aria-live="polite">{messages.length===0?<div><p className="text-sm text-slate-600">Try a project question:</p><div className="mt-3 flex flex-wrap gap-2">{suggestions.map(question=><Button key={question} size="sm" variant="outline" onClick={()=>submit(question)}>{question}</Button>)}</div></div>:<div className="space-y-4">{messages.map((message,index)=><div key={`${message.role}-${index}`} className={message.role==='user'?'ml-8 rounded border border-slate-200 bg-slate-50 p-3 text-sm':'mr-3 text-sm leading-6 text-slate-700'}>{message.role==='assistant'?<ReactMarkdown remarkPlugins={[remarkGfm]} disallowedElements={['html','script','img']} skipHtml>{message.content}</ReactMarkdown>:message.content}</div>)}{loading&&<p role="status" className="text-sm text-slate-600">Thinking…</p>}<div ref={messagesEndRef}/></div>}</div><div className="border-t border-slate-200 p-4"><form onSubmit={event=>{event.preventDefault();submit();}} className="flex gap-2"><input ref={inputRef} aria-label="Ask a project question" maxLength={2000} value={input} onChange={event=>setInput(event.target.value)} placeholder="Ask about the data or methodology" className="min-w-0 flex-1 rounded border border-slate-300 px-3 text-sm"/><Button size="icon" type="submit" disabled={loading||!input.trim()} aria-label="Send question"><Send size={16}/></Button></form><div className="mt-3 flex items-center justify-between gap-2"><div className="flex gap-1"><Button size="sm" variant="ghost" onClick={copy} disabled={!messages.some(m=>m.role==='assistant')}><Clipboard size={14}/>Copy answer</Button><Button size="sm" variant="ghost" onClick={()=>setMessages([])} disabled={!messages.length}><Trash2 size={14}/>Clear chat</Button></div></div><p className="mt-2 text-xs leading-5 text-slate-500">Answers explain public QIP reporting and this project. This is not live hospital data or medical advice.</p></div></SheetContent></Sheet></>;
}
