import type { ExplorerData, ExplorerRecord } from '@/lib/types';
import { auditMetrics, primaryEdRate, rate } from '@/lib/audit-helpers';

export function ReportingQuality({ data, records }: { data: ExplorerData; records: ExplorerRecord[] }) {
  const metrics = auditMetrics(data, records);
  const primary = primaryEdRate(data, records);
  return <section className="space-y-5" aria-labelledby="reporting-quality-title">
    <div><h2 id="reporting-quality-title" className="text-xl font-semibold text-slate-950">Reporting quality and audit</h2>
      <p className="mt-1 max-w-3xl text-sm leading-6 text-slate-600">The source audit uses a fixed denominator across all exported rows. ED figures below are filtered diagnostic metrics and should not be read as coverage of all Ontario hospitals.</p></div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{metrics.map((m) => <div key={m.label} className="rounded-md border border-slate-200 bg-white p-4"><p className="text-xs font-medium uppercase tracking-wide text-slate-500">{m.label}</p><p className="mt-2 text-2xl font-semibold text-slate-950">{m.value}</p>{m.detail && <p className="mt-1 text-xs text-slate-500">{m.detail}</p>}</div>)}</div>
    <div className="rounded-md border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-950"><p className="font-semibold">Reporting verification status: Not comparable</p><p>Numeric values may exist in both workplan and progress records, but the reporting periods could not be verified as directly comparable. The dashboard therefore does not calculate outcome or effectiveness metrics.</p></div>
    <div className="rounded-md border border-slate-200 bg-white p-4"><p className="text-sm font-semibold text-slate-900">Primary filtered ED cycle window</p><p className="mt-1 text-sm text-slate-600">2025/26 workplan → 2026/27 progress: {primary.matched} matched cycles; {primary.numeric} matched cycles with numeric values available. Dates are verified for {primary.verified} of {primary.total} selected primary cycles; verified dates do not establish comparability. Comparisons remain Not comparable.</p></div>
    <div tabIndex={0} role="region" aria-label="Source match coverage table" className="overflow-x-auto rounded-md border border-slate-200 bg-white"><table className="min-w-full text-left text-sm"><caption className="p-4 text-left text-xs text-slate-500">Unfiltered source audit pair diagnostics; ED filtered metrics are shown above.</caption><thead className="border-b border-slate-200 bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">Cycle pair</th><th className="px-4 py-3">Scope</th><th className="px-4 py-3">Matched / candidates</th><th className="px-4 py-3">Numeric / candidates</th></tr></thead><tbody>{data.audit.pairs.map((p) => <tr key={`${p.year}-${p.scope}`} className="border-b border-slate-100 last:border-0"><td className="px-4 py-3">{p.year} → following progress</td><td className="px-4 py-3">{p.scope}</td><td className="px-4 py-3">{rate(p.matched, p.denominator)}</td><td className="px-4 py-3">{rate(p.numericPairs, p.denominator)}</td></tr>)}</tbody></table></div>
    <p className="text-xs leading-5 text-slate-500">Ambiguous matches, excluded test rows, missing models, unknown values, and implementation conflicts are retained in the source records for review. A match or numeric value is not evidence of an effect.</p>
  </section>;
}
